-- AlterEnum
ALTER TYPE "DpRequestType" ADD VALUE 'ADM_VIAGENS';
ALTER TYPE "DpRequestType" ADD VALUE 'ADM_EPI_FARDAMENTO';
ALTER TYPE "DpRequestType" ADD VALUE 'ADM_MANUTENCAO_ESCRITORIO';
ALTER TYPE "DpRequestType" ADD VALUE 'ADM_MATERIAL_ESCRITORIO';
ALTER TYPE "DpRequestType" ADD VALUE 'ADM_INFORMATICA';
ALTER TYPE "DpRequestType" ADD VALUE 'ADM_TREINAMENTOS_NR';
