ALTER TYPE "DpRequestType" ADD VALUE 'ADMISSAO';
ALTER TYPE "DpRequestType" ADD VALUE 'ALTERACAO_FUNCAO_SALARIO';
ALTER TYPE "DpRequestType" ADD VALUE 'ADVERTENCIA_SUSPENSAO';
ALTER TYPE "DpRequestType" ADD VALUE 'RETIFICACAO_ALOCACAO';
ALTER TYPE "DpRequestType" ADD VALUE 'HORA_EXTRA';
ALTER TYPE "DpRequestType" ADD VALUE 'BENEFICIOS_VIAGEM';

ALTER TABLE "dp_requests" ADD COLUMN "details" JSONB;
