export const CARGOS_LIST = [
  'Ajudante',
  'Almoxarife',
  'Analista',
  'Assistente',
  'Auxiliar',
  'Babá',
  'Bombeiro hidráulico',
  'Comprador jr',
  'Coordenador(a)',
  'Diretor',
  'Eletricista',
  'Eletrotécnico',
  'Encarregado',
  'Engenheiro',
  'Estagiário(a)',
  'Função',
  'Gerente',
  'Gesseiro',
  'Impermeabilizador',
  'Jovem aprendiz',
  'Marceneiro',
  'Mestre de obras',
  'Motorista',
  'Oficial de manutenção',
  'Orçamentista',
  'Pedreiro',
  'Pintor',
  'Servente',
  'Serviços administrativos',
  'Serviços gerais',
  'Supervisor',
  'Técnico',
  'Vidraceiro',
  'Administrador' // Cargo especial que não aparece na lista de seleção
];

// Lista de cargos disponíveis para seleção (sem Administrador)
export const CARGOS_AVAILABLE = CARGOS_LIST.filter(cargo => cargo !== 'Administrador');
