ALTER TYPE "DpRequestStatus" ADD VALUE 'IN_FINANCEIRO';
ALTER TYPE "DpRequestStatus" ADD VALUE 'WAITING_RETURN_ACCOUNTING';
ALTER TYPE "DpRequestStatus" ADD VALUE 'WAITING_RETURN_ADM_TST';
ALTER TYPE "DpRequestStatus" ADD VALUE 'WAITING_RETURN_ENGINEERING';

ALTER TABLE "dp_requests" ADD COLUMN "dpResponsibleNote" TEXT;
